import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fixture } from './fixture.mjs';

test('agent forwards HTTP and CDP through a relay and recovers without replay', { timeout: 90000 }, async t => {
  const resources = await fixture();
  const { local, relay } = resources;
  t.after(() => resources.close());
  const cwd = resolve('.tmp/local-api-proxy-test');
  await mkdir(cwd, { recursive: true });
  await writeFile(resolve(cwd, 'proxy.json'), JSON.stringify(resources.configuration));
  const historyPath = resolve(cwd, 'communication.json');
  const saved = 'existing file must not be read or overwritten';
  await writeFile(historyPath, saved);
  const agent = spawn(resolve('build/agent.exe'), [], { cwd, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'] });
  let output = '';
  agent.stdout.on('data', b => { output += b; });
  agent.stderr.on('data', b => { output += b; });
  t.after(async () => { agent.kill(); await writeFile(resolve(cwd, 'agent.log'), output); });
  const { Gateway } = await import('../gateway/gateway.mjs');
  const gateway = new Gateway(`ws://127.0.0.1:${relay.address().port}/?role=server`);
  t.after(() => gateway.close());
  await gateway.ready();
  const body = Buffer.from('中文\u0000binary');
  const response = await gateway.request({ method: 'POST', path: '/echo', headers: [], body });
  assert.equal(response.status, 201, output);
  assert.deepEqual(response.body, body);
  assert.equal(response.headers.filter(h => h.name === 'set-cookie').length, 2);
  const large = await gateway.request({ method: 'GET', path: '/large', headers: [], body: Buffer.alloc(0) });
  assert.deepEqual(large.body, Buffer.alloc(1500000, 255));
  const tunnel = await gateway.openTunnel({ path: '/devtools/browser/test', port: resources.echo.address().port, headers: [] });
  const message = once(tunnel, 'message');
  tunnel.send(Buffer.from('你好 CDP'), false);
  const [data, binary] = await message;
  assert.equal(data.toString(), '你好 CDP');
  assert.equal(binary, false);
  const binaryMessage = once(tunnel, 'message');
  tunnel.send(Buffer.from([0, 255, 127]), true);
  assert.deepEqual((await binaryMessage)[0], Buffer.from([0, 255, 127]));
  tunnel.close();
  const uploaded = Buffer.alloc(150000, 254);
  assert.deepEqual((await gateway.request({ method: 'POST', path: '/upload', body: uploaded })).body, uploaded);
  await Promise.all(Array.from({ length: 4 }, async (_, i) => {
    const content = Buffer.from(String(i));
    assert.deepEqual((await gateway.request({ method: 'POST', path: '/concurrent', body: content })).body, content);
  }));
  await assert.rejects(gateway.request({ method: 'GET', path: '//elsewhere/' }), /absolute path/);
  const abort = new AbortController();
  const pending = gateway.request({ method: 'GET', path: '/never', signal: abort.signal });
  const cancelled = assert.rejects(pending, /cancelled/);
  abort.abort();
  await cancelled;
  assert.equal((await gateway.request({ method: 'GET', path: '/after-cancel' })).status, 201);
  const interrupted = gateway.request({ method: 'POST', path: '/never' });
  const rejected = assert.rejects(interrupted, /reconnected/);
  const recovered = once(gateway, 'ready');
  for (const client of relay.clients) if (client.role === 'client') client.terminate();
  await recovered;
  await rejected;
  assert.equal((await gateway.request({ method: 'GET', path: '/after-reconnect' })).status, 201);
  assert.equal(await readFile(historyPath, 'utf8'), saved);
  assert.ok(!output.includes('通讯记录读取失败'));
});
